[package]
name = "crop"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "create"
harness = false
