[package]
name = "crop"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"

[dependencies]
str_indices = "0.4.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "create"
harness = false

[[bench]]
name = "iterators"
harness = false
