[package]
name = "crop"
version = "0.1.0"
authors = ["Riccardo Mazzarini <me@noib3.dev>"]
edition = "2021"

[package.metadata.docs.rs]
features = ["graphemes"]

[features]
graphemes = ["dep:unicode-segmentation"]

# Private features
integration_tests = []

[dependencies]
smallvec = { version = "1.10.0", features = ["const_generics"] }
str_indices = "0.4.0"
unicode-segmentation = { version = "1.10.0", optional = true }

[dev-dependencies]
criterion = "0.4"
rand = "0.8"
ropey = { git = "https://github.com/cessen/ropey", rev = "633143d" }
xi-rope = { git = "https://github.com/xi-editor/xi-editor", rev = "7cd12f4" }

[[bench]]
name = "creation"
harness = false

[[bench]]
name = "iterators"
harness = false

[[bench]]
name = "slicing"
harness = false
