[package]
name = "crop"
version = "0.1.0"
authors = ["Riccardo Mazzarini <me@noib3.dev>"]
edition = "2021"

[features]
default = ["graphemes"]
graphemes = ["dep:unicode-segmentation"]

[dependencies]
str_indices = "0.4.0"
unicode-segmentation = { version = "1.10", optional = true }

[dev-dependencies]
criterion = "0.4"
rand = "0.8"

[[bench]]
name = "create"
harness = false

[[bench]]
name = "iterators"
harness = false

[[bench]]
name = "slicing"
harness = false
